
services:
  python-backend:
    build:
      context: ./python
    ports:
      - "3001:3001"
    environment:
      - PYTHON_ENV=production
      - PY_PORT=${PY_PORT}
      - PY_CORS_ORIGIN=${PY_CORS_ORIGIN}
  
  express-backend:
    build: 
      context: ./express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EX_PORT=${EX_PORT}
      - ORIGIN_ACCESS_URL=${ORIGIN_ACCESS_URL}
      - MODEL_API_URL=${MODEL_API_URL}
    
  nginx:
    image: nginx:latest
    ports:
      - "443:443"  #https
      - "80:80"    #http 

    volumes:
      - /home/ec2-user/certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf 
    
    depends_on:
      - express-backend
