name: Deploy  to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy Bckend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<EOF
            #Ensure Docker & Docker Compose are installed (if not installed)
            sudo yum install -y git
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -aG docker \$USER
            sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            #Set Environment variables for session
            export PY_PORT="${{ secrets.PY_PORT }}"
            export PY_CORS_ORIGIN="${{ secrets.PY_CORS_ORIGIN }}"
            export EX_PORT="${{ secrets.EX_PORT }}"
            export ORIGIN_ACCESS_URL="${{ secrets.ORIGIN_ACCESS_URL }}"

            git pull origin main
            cd ./ai-recipe-finder/backend/

            #Stop current container and rebuild and restart containers using docker-compose
            docker-compose down
            docker-compose up -d --build
          EOF